{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Critical Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"critical_violations\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   ]
  },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
  { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 8 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 8 } },
  { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 14 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Major Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"major_violations\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   ]
  },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
  { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 8 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 8 } },
  { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 14 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 2 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 2 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 8 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 14 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 15 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 15 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 21 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Quality Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 } }
   ]
  },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 14 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 15 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 15 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 21 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New Bugs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"new_bugs\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: int(v: r._value)\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Quality Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 } }
   ]
  },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 22 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 23 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 23 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 29 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "New Bugs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Quality Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 } }
   ]
  },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 22 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 23 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 23 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 29 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "New Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"new_violations\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: int(v: r._value)\r\n    }))\r\n"
    }
   ]
  },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "New Bugs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Quality Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 } }
   ]
  },
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 22 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 23 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 23 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 29 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Issue Severity Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 } },
    { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 } },
    { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 2 } }
   ]
  },
  {
   "title": "Quality Sanpshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 } },
    { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 49 } },
    { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 49 } },
    { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 } },
    { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 55 } }
   ]
  },
  {
   "title": "Quality Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 } }
   ]
  },
  {
   "title": "Quality Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "title": "New Bugs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 } },
    { "title": "New Issues", "gridPos": { "h": 8, "w": 11, "x": 12, "y": 13 } }
   ]
  }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Build Status", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
  { "title": "Code Smells", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 8 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 12, "w": 10, "x": 13, "y": 8 } },
  { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "title": "New Bugs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 } },
  { "title": "New Issues", "gridPos": { "h": 8, "w": 11, "x": 12, "y": 28 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 11, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 8, "w": 11, "x": 12, "y": 26 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 7, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "New Code Coverage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"new_coverage\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Hotspots Reviewed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"bugs\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  {
   "title": "Bugs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"bugs\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 7, "x": 16, "y": 9 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 15 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 26 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 26 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 32 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "Harmonia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "Harmonia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "harmonia" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "iBeauty",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "iBeauty",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "IBeauty - APIs", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 }, "options": { "content": "<h1>IBeauty - APIs</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "iBeauty",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "<h1>IBeauty - APIs</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 3 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 9 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 } }
 ]
}
{
 "title": "iBeauty",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "ibeauty-api" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 }, "options": { "content": "<h1>IBeauty - APIs</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 3 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 9 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 } }
 ]
}
{
 "title": "Harmonia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "harmonia" }
  ]
 },
 "panels": [
  { "title": "New panel", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 }, "options": { "content": "<h1>Harmonia</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "Harmonia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "harmonia" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 }, "options": { "content": "<h1>Harmonia</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 3 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 9 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 }, "options": { "content": "<h1>One SFA</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 7 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 7 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 12 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 24 } }
 ]
}
{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 }, "options": { "content": "<h1>One SFA</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 3 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 9 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 } }
 ]
}
{
 "title": "Harmonia",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "harmonia" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 }, "options": { "content": "<h1>Harmonia</h1>" } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Blocker Issue", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 } },
  { "title": "Critical Issues", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 } },
  { "title": "Major Issues", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 } },
  { "title": "Bugs", "gridPos": { "h": 5, "w": 6, "x": 17, "y": 3 } },
  { "title": "Quality Sanpshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Build Status", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 } },
  { "title": "Code Smells", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 } },
  { "title": "Coverage Percentage", "gridPos": { "h": 10, "w": 10, "x": 13, "y": 9 } },
  { "title": "Reliability Rating", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 } },
  { "title": "Security Rating", "gridPos": { "h": 5, "w": 7, "x": 6, "y": 14 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Duplicate Lines ", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 } },
  { "title": "New Code Coverage", "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "New Bugs", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 } },
  { "title": "New Issues", "gridPos": { "h": 9, "w": 11, "x": 12, "y": 26 } }
 ]
}