{
 "title": "Harmonia",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "<h1> Harmonia Chatbot </h1>" } },
  {
   "title": "Build Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"alert_status\")\n  |> filter(fn: (r) => r.project == \"nasapmena-inno-harmoniaai\")\n"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"security_rating\")\n"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"reliability_rating\")\n"
    }
   ]
  },
  {
   "title": "Coverage Percentage",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"coverage\")\n  |> filter(fn: (r) => r.project == \"nasapmena-inno-harmoniaai\")\n"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"code_smells\")\n  |> filter(fn: (r) => r.project == \"nasapmena-inno-harmoniaai\")\n"
    }
   ]
  },
  {
   "title": "Duplicate Lines ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"harmonia\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"duplicated_lines_density\")\n  |> filter(fn: (r) => r.project == \"nasapmena-inno-harmoniaai\")\n"
    }
   ]
  }
 ]
}