{
 "title": "iBeauty",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "<h1> IBeauty - APIs </h1>" } },
  {
   "title": "Build Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"alert_status\")\n"
    }
   ]
  },
  {
   "title": "Security Rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"security_rating\")\n"
    }
   ]
  },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"reliability_rating\")\n"
    }
   ]
  },
  {
   "title": "Coverage Percentage",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"coverage\")\n\n"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"code_smells\")\n"
    }
   ]
  },
  {
   "title": "Duplicate Line Density",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ibeauty-api\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"duplicated_lines_density\")\n"
    }
   ]
  }
 ]
}