{
 "title": "oneSFA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> keep(columns: [\"project\"])\r\n  |> distinct(column: \"project\")\r\n"
    }
   },
   { "name": "bucket", "query": "onesfa" }
  ]
 },
 "panels": [
  { "title": "Quality Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 } },
  { "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 } },
  { "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 } },
  {
   "title": "Reliability Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"reliability_rating\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   ]
  },
  { "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 } },
  { "title": "Quality Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 } },
  {
   "title": "New Issues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"new_violations\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: int(v: r._value)\r\n  }))\r\n"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 } },
  { "title": "Quality Ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 } },
  { "title": "Issue Severity Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  { "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 } },
  { "gridPos": { "h": 3, "w": 7, "x": 6, "y": 25 } },
  {
   "title": "Major Issues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._field == \"major_violations\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])\r\n"
    }
   ]
  }
 ]
}